- name: install yum from list
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{ install_packages_centos }}"

- shell: yum -y update
- shell: yum -y groupinstall development

- block: # download docker

  - name: install yum for CentOS
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: Add yum repository
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: install docker
    yum:
      name: docker-ce
      state: present

- block: # download chrome

  - name: download chrome
    get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      dest: /tmp

  - name: install chrome
    yum:
      name: /tmp/google-chrome-stable_current_x86_64.rpm


- block: # download atom

  - name: download atom
    get_url:
      url: https://atom.io/download/rpm
      dest: /tmp/atom.rpm

  - name: install atom
    yum:
      name: /tmp/atom.rpm
