- name: install python2-dnf
  shell: dnf install python2-dnf -y

- name: install dnf from list
  dnf:
    name: "{{item}}"
    state: present
  with_items: "{{ install_packages_fedora }}"

- name: add repo
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: install docker
  dnf:
    name: docker-ce
    state: present

- block: # download chrome

  - get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      dest: /opt

  - yum:
      name: /opt/google-chrome-stable_current_x86_64.rpm

- block: # download atom

  - get_url:
      url: https://atom.io/download/rpm
      dest: /opt/atom.rpm

  - yum:
      name: /opt/atom.rpm
