- name: install yum from list
  dnf:
    name: "{{item}}"
    state: present
  with_items: "{{ install_packages_centos }}"

- shell: dnf -y update
#- shell: dnf -y groupinstall development

- block: # download docker

  - name: install yum for CentOS
    dnf:
      name: "{{item}}"
      state: present
    with_items:
      - dnf-plugins-core

  - name: Add yum repository
    shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

  - name: install docker
    dnf:
      name: docker-ce
      state: present

- block: # download chrome

  - name: download chrome
    get_url:
      url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      dest: /tmp

  - name: install chrome
    dnf:
      name: /tmp/google-chrome-stable_current_x86_64.rpm


- block: # download atom

  - name: download atom
    get_url:
      url: https://atom.io/download/rpm
      dest: /tmp/atom.rpm

  - name: install atom
    dnf:
      name: /tmp/atom.rpm

# - block: # install gitkraken
        

- name: install snap
  dnf:
   name: snapd
   state: present

- name: create link
  ignore_errors: yes
  shell: ln -s /var/lib/snapd/snap /snap

- name: install gitkraken
  shell: snap install gitkraken
