---

- block:

  - include: centos.yml

  when: ansible_os_family == "RedHat"

- block:

  - name: for Debian
    include: debian.yml

  when: ansible_os_family == "Debian"

- block: # Python 3

  # - name: download python 3
  #   get_url:
  #     url: https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz
  #     dest: /tmp

  - name: unarchive Python 3
    unarchive:
      # src: /tmp/Python-3.7.0.tar.xz
      src: https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz
      dest: /tmp
      remote_src: yes

  - name: install python 3
    shell: |
      cd /tmp/Python-3.7.0
      ./configure
      make
      make install

- name: install pip packets
  shell: pip3 install {{item}}
  with_items: "{{ pip_packeges }}"

- block: # Docker

  - name: download docker-compose
    shell: curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

  - name: chmod for docker-compose
    file:
      path: /usr/local/bin/docker-compose
      state: file
      mode: 0755

- block: # Maven

  - name: unarchive maven
    unarchive:
      src: http://apache-mirror.rbc.ru/pub/apache/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      dest: /opt
      remote_src: yes

  - name: create link maven
    file:
      path: /opt/maven
      src: /opt/apache-maven-3.5.4
      state: link

  - name: create /etc/profile.d/maven.sh
    file:
      path: /etc/profile.d/maven.sh
      state: touch
      mode: 0755

  - name: add PATH for maven
    lineinfile:
      path: /etc/profile.d/maven.sh
      line: PATH=$PATH:/opt/maven/bin

- block: # Postman

  - name: unarchive Postman
    unarchive:
      src: https://dl.pstmn.io/download/latest/linux64
      dest: /opt
      remote_src: yes

  - name: create link for Postman
    file:
      path: /opt/Postman-linux-x64
      src: /opt/Postman
      state: link

- block: # Packer

  - name: unarchive packer
    unarchive:
      src: https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip?_ga=2.125730440.305266263.1514202778-1122507811.1514202778
      dest: /bin
      remote_src: yes

- block: # Terraform

  - name: unarchive terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip?_ga=2.119035913.1857397525.1514202783-2102502424.1514202783
      dest: /bin
      remote_src: yes

- block: # IDEA

  - name: download IDEA
    unarchive:
      src: https://download.jetbrains.com/idea/ideaIC-2018.1.5.tar.gz
      dest: /opt
      remote_src: yes
