---

  - name: stop selinux
    lineinfile:
      dest: /etc/selinux/config
      regexp: ^SELINUX=enforcing
      line: SELINUX=disabled
      backrefs: yes
      state: present
    when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" or ansible_distribution == "Fedora"

  - name: install yum from list
    yum:
      name: "{{item}}"
      state: present
    with_items: "{{ install_packages }}"
    when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"

  - name: install dnf from list
    dnf:
      name: "{{item}}"
      state: present
    with_items: "{{ install_packages }}"
    when: ansible_distribution == "Fedora"

  - name: install apt from list
    apt:
      name: "{{item}}"
      state: present
      update_cache: yes
    with_items: "{{ install_packages }}"
    when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu" or ansible_distribution == "astra linux se"

  - name: install pip packets
    shell: pip3 install {{item}}
    with_items: "{{ pip_packeges }}"

  - name: install maven
    shell: |
      cd /opt
      wget http://mirror.linux-ia64.org/apache/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
      tar -xzvf apache-maven-3.5.0-bin.tar.gz
      echo "PATH=$PATH:/opt/apache-maven-3.5.0/bin" >> /etc/profile.d/01_jdk8.sh
      rm apache-maven-3.5.0-bin.tar.gz

  - name: download chrome
    shell: |
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      dnf install google-chrome-stable_current_x86_64.rpm

  - name: download atom
    shell: |
      wget https://atom.io/download/rpm
      dnf install rpm

  - name: download Postman
    shell: |
      cd /opt
      wget https://dl.pstmn.io/download/latest/linux64
      tar xzvf Postman-linux-x64-5.5.0.tar.gz
      mv Postman-linux-x64-5.5.0/Postman Postman

  - name: download gitkraken
    shell: |
      cd /opt
      wget https://release.gitkraken.com/linux/gitkraken-amd64.tar.gz
      tar xzvf gitkraken-amd64.tar.gz
      cd gitkraken
      sudo ln -s /usr/lib64/libcurl.so.4 libcurl-gnutls.so.4

  - name: download packer
    shell: |
      cd /opt
      wget https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_linux_amd64.zip?_ga=2.125730440.305266263.1514202778-1122507811.1514202778
      unzip packer_1.1.3_linux_amd64.zip
      mv packer_1.1.3_linux_amd64/packer /bin/packer
      rm -rf packer*

  - name: download terraform
    shell: |
      cd /opt
      wget https://releases.hashicorp.com/terraform/0.11.1/terraform_0.11.1_linux_amd64.zip?_ga=2.119035913.1857397525.1514202783-2102502424.1514202783
      unzip packer_1.1.3_linux_amd64.zip
      mv terraform_0.11.1_linux_amd64/terraform /bin/terraform
      rm -rf terraform*
