---
install_packages_centos:
  - wget
  - unzip
  - tar
  - git
  - mc
  - python-requests
  - libselinux-python
  - cifs-utils
  - gcc
  - gcc-c++
  - yum-utils 
  - openssl-devel
  - sqlite-devel
  - zlib
  - zlib-devel
  - libffi-devel
  # - nfs-common

install_packages_debian:
  - wget
  - unzip
  - tar
  - git
  - python-requests
  - mc
  - apt-transport-https
  - ca-certificates
  - gnupg2
  - software-properties-common

pip_packeges:
  - pywinrm
  - psycopg2-binary
  - pyTelegramBotAPI
  - jenkinsapi
  - pysphere
  - xlrd
  - python-dateutil
  - gspread
  - oauth2client
  - pysocks
