---
  install_packages:
    - wget
    - unzip
    - tar
    - java
    - python2
    - python3
    - git
    # - gitkraken
    # - google-chrome
    - python-requests
    - python-setuptools
    - docker
    - remmina
    - mc
    - libselinux-python
    - pgadmin3

  pip_packeges:
    - pywinrm
    - psycopg2
    # - logging
    - pyTelegramBotAPI
    - jenkinsapi
